# Generated by Django 3.0.5 on 2020-05-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_list',
            options={'verbose_name': 'Task List', 'verbose_name_plural': 'Task Lists'},
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='task_lists.Task_List'),
        ),
    ]
