# Generated by Django 3.0.5 on 2020-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_lists', '0003_auto_20200529_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Group', 'Group')], default='', max_length=254),
        ),
    ]
