# Generated by Django 3.0.5 on 2020-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_lists', '0004_task_list_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='parent_list',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
