# Generated by Django 3.0.5 on 2020-05-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_lists', '0005_task_list_parent_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=25),
        ),
    ]
