# Generated by Django 3.0.5 on 2020-05-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_lists', '0006_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25),
        ),
    ]
