# Generated by Django 3.0.5 on 2020-06-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_lists', '0008_auto_20200530_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
