# Generated by Django 3.0.5 on 2020-06-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_lists', '0009_auto_20200601_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='sort_by',
            field=models.CharField(choices=[('Ascending', 'Ascending'), ('Descending', 'Descending')], default='Ascending', max_length=254),
        ),
    ]
