# Generated by Django 3.0.7 on 2020-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_lists', '0011_task_list_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_list_users',
            options={'verbose_name': 'Task List User', 'verbose_name_plural': 'Task List Users'},
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25),
        ),
    ]
