# Generated by Django 3.0.7 on 2020-06-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_lists', '0012_auto_20200607_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='list_owner',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
